config/routes.rb
Rails.application.routes.draw do




  #get '/invite', to: 'groups#invite', constraint: lambda {|request|Organisation.subdomains.include?(request.subdomains.first)}


  devise_for :organisations, path: 'organisations' , :controllers => { registrations: "registrations" }

  devise_for :users, path: 'users' , :controllers => { registration: "signups" }


  root 'static_pages#home'

  get '/home', to: 'static_pages#home'




  resources :users, :path_names => { :show => 'user'} ,  only: [:show, :edit, :update] do
     collection do
        get :skillsearch
        get :skills
        get :memberprofiles
        get :memberprofilesearch
       end
  end



  resources :organisations do
    collection do
       get :email
       get :sms
       get :send_message
       post :send_sms
       get :send_email
    end
     resources :membershipdata

     resources :events

     resources :fundraisings
  end

  devise_scope :organisation do
     get '/dashboard', to: 'organisations#index'
  end

  devise_scope :user do
     get '/userfeed', to: 'groups#index'
  end


  resources :networks

  resources :fundraisings do
    collection do
     get :single_page
    end
  end

  resources :membershipdata do
    collection do
      get :members
      post :import
    end
  end


  resources :events do
    collection do
      get :eventsearch
    end
  end

  resources :jobs do
    collection do
      get :jobsearch
    end
  end

   resources :groups do
     collection do
      get :events

      get :jobs

      get :skills

      get :fundraising

      get :network

      get :directory
      end
  end

  resources :announcements
  resources :memberships

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<%# <center > </center> %>


 <div class="container">
  <div class="row">
     <div class="col-md-6 col-md-offset-2">
      <center>   <h1>NectHub - Set up your organisation </h1> </center>
     </div>
     <br>
     <br>
     <br>
  </div>
  <div class="row">
  <div class="col-md-6 col-md-offset-2">
 <%= link_to "Sign Up As an Organisation" ,  new_organisation_registration_path , :class => "btn btn-primary btn-block  btn-lg"  %> 
  </div>
  </div>
 </div>