config/routes.rb
Rails.application.routes.draw do




  #get '/invite', to: 'groups#invite', constraint: lambda {|request|Organisation.subdomains.include?(request.subdomains.first)}


  devise_for :organisations, path: 'organisations' , :controllers => { registrations: "registrations" }

  devise_for :users, path: 'users' , :controllers => { registration: "signups" }


  root 'static_pages#home'

  get '/home', to: 'static_pages#home'




  resources :users, :path_names => { :show => 'user'} ,  only: [:show, :edit, :update] do
     collection do
        get :skillsearch
        get :skills
        get :memberprofiles
        get :memberprofilesearch
       end
  end



  resources :organisations do
    collection do
       get :email
       get :sms
       get :send_message
       post :send_sms
       get :send_email
    end
     resources :membershipdata

     resources :events

     resources :fundraisings
  end

  devise_scope :organisation do
     get '/dashboard', to: 'organisations#index'
  end

  devise_scope :user do
     get '/userfeed', to: 'groups#index'
  end


  resources :networks

  resources :fundraisings do
    collection do
     get :single_page
    end
  end

  resources :membershipdata do
    collection do
      get :members
      post :import
    end
  end


  resources :events do
    collection do
      get :eventsearch
    end
  end

  resources :jobs do
    collection do
      get :jobsearch
    end
  end

   resources :groups do
     collection do
      get :events

      get :jobs

      get :skills

      get :fundraising

      get :network

      get :directory
      end
  end

  resources :announcements
  resources :memberships

end

app/views/announcements/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Announcements</h2>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content">

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="row">
                    <div class="col-lg-6" align="center">
                        <h2>Post Announcements</h2>
                    </div>
                    <div class="col-lg-6" align="center">
                        <%#<a href="" class="btn btn-primary">New Event</a>%>
                        <%= link_to "New Announcement" , new_announcement_path , :class => "btn btn-primary"  %>
                    </div>
                </div>

                </div>

            <div class="ibox-content text-center css-animation-box">
                <br /><br />
                <h1 class="text-navy">Your Announcements</h1>
                <br /><br />


            
                <div class="row">
                    <% for announcement in @announcements do %>
                    <div class="col-lg-4">
                        <div class="ibox" style="border: 1px solid #f1e4e4; padding: 0px;">
                            <div class="ibox-title">
                                <h5><%= announcement.try(:title)%></h5>
                            </div>
                            <div class="ibox-content">

                                <br />
                                <h4>Info</h4>
                                <p>
                                    <%= announcement.try(:description)%>
                                </p>
                                <br />

                            </div>
                        </div>
                    </div>
                    <% end %>
                </div>
            
            </div>
            </div>
        </div>
    </div>

</div>

<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $('.summernote').summernote();

    var edit = function () {
        $('.click2edit').summernote({ focus: true });
    };

    $("#edit").click(function () {
        $('.click2edit').summernote({ focus: true });
    });

    $("#save").click(function () {
        var aHTML = $('.click2edit').code(); //save HTML If you need(aHTML: array).
        $('.click2edit').destroy();
    });

});

</script>

<% end %>