config/routes.rb
Rails.application.routes.draw do




  #get '/invite', to: 'groups#invite', constraint: lambda {|request|Organisation.subdomains.include?(request.subdomains.first)}


  devise_for :organisations, path: 'organisations' , :controllers => { registrations: "registrations" }

  devise_for :users, path: 'users' , :controllers => { registration: "signups" }


  root 'static_pages#home'

  get '/home', to: 'static_pages#home'




  resources :users, :path_names => { :show => 'user'} ,  only: [:show, :edit, :update] do
     collection do
        get :skillsearch
        get :skills
        get :memberprofiles
        get :memberprofilesearch
       end
  end



  resources :organisations do
    collection do
       get :email
       get :sms
       get :send_message
       post :send_sms
       get :send_email
    end
     resources :membershipdata

     resources :events

     resources :fundraisings
  end

  devise_scope :organisation do
     get '/dashboard', to: 'organisations#index'
  end

  devise_scope :user do
     get '/userfeed', to: 'groups#index'
  end


  resources :networks

  resources :fundraisings do
    collection do
     get :single_page
    end
  end

  resources :membershipdata do
    collection do
      get :members
      post :import
    end
  end


  resources :events do
    collection do
      get :eventsearch
    end
  end

  resources :jobs do
    collection do
      get :jobsearch
    end
  end

   resources :groups do
     collection do
      get :events

      get :jobs

      get :skills

      get :fundraising

      get :network

      get :directory
      end
  end

  resources :announcements
  resources :memberships

end

app/models/fundraising.rb
class Fundraising < ApplicationRecord
  mount_uploader :campaign_pic, CampaignPicUploader

  belongs_to :organisation


end

app/controllers/fundraisings_controller.rb
class FundraisingsController < ApplicationController
  before_action :authenticate_organisation!

  layout "organisations"


  def index

     @fundraisings = current_organisation.fundraisings
  end

  def new
    @fundraising = Fundraising.new
  end

  def create
    @fundraising = current_organisation.fundraisings.build(fundraising_params)
       if @fundraising.save
         #flash[:notice] = "Fundraising campaign created successfully"

        redirect_to fundraisings_path
        else
          # flash[:alert] = "Something went wrong"

           redirect_to new_fundraising_path
        end

  end

  def show
    @fundraising = Fundraising.find(params[:id])
  end

  private
  def fundraising_params
    params.require(:fundraising).permit(:title,:description,:city,:country,:campaign_pic)
  end

end

app/helpers/fundraisings_helper.rb
module FundraisingsHelper
end

app/views/fundraisings/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Fundraising</h2>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeIn">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <div class="row">
                    <div class="col-lg-6" align="center">
                        <h2>Create new fundraising campaign</h2>
                    </div>
                    <div class="col-lg-6" align="center">
                        <%#<a href="" class="btn btn-primary">Add New</a>%>
                        <%= link_to "Add New" , new_fundraising_path  , :class => "btn btn-primary" %>
                    </div>
                </div>
            </div>
            <div class="ibox-content text-center css-animation-box"><!-- Copy -->
                <br /><br />
                <h1 class="text-navy">Your campaigns</h1>
                <br /><br />

                <div class="row">

               <% @fundraisings.each do |fundraising|%>
               <div class="col-lg-4">
            <div class="ibox" style="border: 1px solid #f1e4e4; padding: 0px;">

                <div class="ibox-title">
                    <h5>
                    <%= fundraising.try(:title) %>
                    </h5>
                </div>
                <div class="ibox-content">
                    <div><!-- Image here -->
                    <%= image_tag fundraising.campaign_pic.thumb.url if fundraising.campaign_pic? %>

                    </div>
                    <br />
                    <h4>Info</h4>
                    <p>
                        <%= fundraising.try(:description) %>
                    </p>
                    <br />
                    <div><!--
                        <span>Status of funds:</span>
                        <div class="stat-percent">48%</div>
                        <div class="progress progress-mini">
                            <div style="width: 48%;" class="progress-bar"></div>
                        </div>-->
                    </div>
                    <br />
                    <div class="row  m-t-sm">
                        <div class="col-sm-4">

                        </div>
                        <div class="col-sm-4">

                        </div>
                        <div class="col-sm-4 text-right">

                             <%= link_to "View More" , {:controller=>"fundraisings", :action=>"show", :id => fundraising.id} , :class => "btn btn-primary"%>

                        </div>
                    </div>

                </div>
            </div>
        </div>
        <% end %>
    </div>
            </div>
        </div>
    </div>

</div>
</div>

<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $('.animation_select').click(function () {
        $('#animation_box').removeAttr('class').attr('class', '');
        var animation = $(this).attr("data-animation");
        $('#animation_box').addClass('animated');
        $('#animation_box').addClass(animation);
        return false;
    });

    
});

</script>

<% end %>

app/views/fundraisings/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Basic Form</h2>
        <ol class="breadcrumb">
            <li>
                <a href="">Home</a>
        </li>
        <li>
            <a>Fundraising</a>
        </li>
        <li class="active">
            <strong>Create Campaign</strong>
        </li>
    </ol>
</div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title" align="center">
                <h2>Create your fundraising campaign</h2>
            </div>
            <div class="ibox-content">

            <%= form_for (@fundraising) , html: {multipart: true } do |f|%>
                         <br />
                    <div align="center">
                        <p>Filling in your fundraising details here will go a long way to help you reach your targeted audience even faster</p>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="container">
                            <div>
                            <label class="control-label">Campaign Title</label>

                            </div>
                            <br />
                            <div class="col-sm-7">
                                <%= f.text_field :title , :placeholder => "Title" , :class => "form-control input-lg m-b"  %>
                                <%#<input type="text" placeholder="Title" class="form-control input-lg m-b" />%>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="container">
                            <div>
                                <label class="control-label">Campaign Description</label>
                            </div>
                            <br />
                            <div class="col-sm-7">
                       <%= f.text_field :description , :placeholder => "Description" , :class => "form-control input-lg m-b"  %>

                                <%#<input type="text" placeholder="Description" class="form-control input-lg m-b" />%>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="container">
                            <div>
                                <label class="control-label">Upload Image</label>
                            </div>
                            <br />
                            <div class="col-sm-7">
                                  <%= f.file_field :campaign_pic , :class => "form-control input-lg m-b" %>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="container">
                            <div>
                                <label class="control-label">City</label>
                            </div>
                            <br />
                            <div class="col-sm-7">
                                 <%= f.text_field :city , :placeholder => "Title" , :class => "form-control input-lg m-b"  %>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="container">
                            <div>
                                <label class="control-label">Country</label>
                            </div>
                            <br />
                            <div class="col-sm-7 ">
                                <%=f.country_select :country , {}, {class: "form-control input-lg m-b" }  %>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="container">
                            <div>
                                <label class="control-label">Campaign Duration (Days)</label>
                            </div>
                            <br />
                            <div class="col-sm-7">
                                <input type="text" placeholder="Duration" class="form-control input-lg m-b" />
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <!-- "a href" link goes back to previous page -->
                            <a href="" class="btn btn-white" >Back</a>
                            <%#<button class="btn btn-primary" type="submit">Start my campaign!</button>%>
                            <%#<%= link_to "Start My Campaign" , single_page_fundraisings_path, :class => "btn btn-primary" %>
                          <%= f.submit "Start My Campaign" , :class => "btn btn-primary" %>

                        </div>
                    </div>

            <% end %>

            </div>
        </div>
    </div>
</div>
</div>

<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green',
    });

});

</script>

<% end %>



app/views/fundraisings/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Project detail</h2>
        <ol class="breadcrumb">
            <li>
                <a href="">Home</a>
        </li>
        <li class="active">
            <strong>View details</strong>
        </li>
    </ol>
</div>
        </div>
<div class="row">
<div class="col-lg-12">
<div class="wrapper wrapper-content animated fadeInUp">
<div class="ibox">
<div class="ibox-title">
<div class="row">
    <div class="col-lg-12">
        <div class="m-b-md">
            <!-- Route to previous page -->
            <%= link_to "Back" , fundraisings_path, :class => "btn btn-white pull-right" %>
            <h2>  <%= @fundraising.try(:title) %>
</h2>
        </div>
    </div>
</div>
</div>
<div class="ibox-content">

<div class="row">
    <div class="col-lg-8">
        <br />
        <dl class="dl-horizontal">
            <dt>Something: </dt>
            <dd>
                <p>Full description is in the backend and will be called from there</p>
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Another thing: </dt>
            <dd>
                <p>Full description is in the backend and will be called from there</p>
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Description: </dt>
            <dd>
                <p><%= @fundraising.try(:description)%></p>
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Status:</dt>
            <dd>
                <div class="progress progress-striped active m-b-sm">
                    <div style="width: 60%;" class="progress-bar"></div>
                </div>
            </dd>
        </dl>
    </div>
    <div class="col-lg-4">

         <%= image_tag @fundraising.campaign_pic.thumb.url if @fundraising.campaign_pic? %>
    </div>
</div>

</div>
</div>
</div>
</div>
</div>


app/views/fundraisings/single_page.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Project detail</h2>
        <ol class="breadcrumb">
            <li>
                <a href="">Home</a>
        </li>
        <li class="active">
            <strong>View details</strong>
        </li>
    </ol>
</div>
        </div>
<div class="row">
<div class="col-lg-12">
<div class="wrapper wrapper-content animated fadeInUp">
<div class="ibox">
<div class="ibox-title">
<div class="row">
    <div class="col-lg-12">
        <div class="m-b-md">
            <a href="#" class="btn btn-white pull-right">Back</a><!-- Route to previous page -->
            <h2>Campaign Title</h2>
        </div>
    </div>
</div>
</div>
<div class="ibox-content">

<div class="row">
    <div class="col-lg-8">
        <br />
        <dl class="dl-horizontal">
            <dt>Something: </dt>
            <dd>
                <p>Full description is in the backend and will be called from there</p>
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Another thing: </dt>
            <dd>
                <p>Full description is in the backend and will be called from there</p>
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Description: </dt>
            <dd>
                <p>Full description is in the backend and will be called from there</p>
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Status:</dt>
            <dd>
                <div class="progress progress-striped active m-b-sm">
                    <div style="width: 60%;" class="progress-bar"></div>
                </div>
            </dd>
        </dl>
    </div>
    <div class="col-lg-4">
        <img alt="image" src="<%= image_url 'http://via.placeholder.com/350x150' %>"/>
    </div>
</div>

</div>
</div>
</div>
</div>
</div>
