config/routes.rb
Rails.application.routes.draw do




  #get '/invite', to: 'groups#invite', constraint: lambda {|request|Organisation.subdomains.include?(request.subdomains.first)}


  devise_for :organisations, path: 'organisations' , :controllers => { registrations: "registrations" }

  devise_for :users, path: 'users' , :controllers => { registration: "signups" }


  root 'static_pages#home'

  get '/home', to: 'static_pages#home'




  resources :users, :path_names => { :show => 'user'} ,  only: [:show, :edit, :update] do
     collection do
        get :skillsearch
        get :skills
        get :memberprofiles
        get :memberprofilesearch
       end
  end



  resources :organisations do
    collection do
       get :email
       get :sms
       get :send_message
       post :send_sms
       get :send_email
    end
     resources :membershipdata

     resources :events

     resources :fundraisings
  end

  devise_scope :organisation do
     get '/dashboard', to: 'organisations#index'
  end

  devise_scope :user do
     get '/userfeed', to: 'groups#index'
  end


  resources :networks

  resources :fundraisings do
    collection do
     get :single_page
    end
  end

  resources :membershipdata do
    collection do
      get :members
      post :import
    end
  end


  resources :events do
    collection do
      get :eventsearch
    end
  end

  resources :jobs do
    collection do
      get :jobsearch
    end
  end

   resources :groups do
     collection do
      get :events

      get :jobs

      get :skills

      get :fundraising

      get :network

      get :directory
      end
  end

  resources :announcements
  resources :memberships

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_organisation!

  #before_action :authenticate_user!



  layout "organisations",  :only => [:network]

  layout "users", :only => [:events,:jobs,:skills,:index]

  def index
     @group_announcements = current_organisation.announcements.all
  end

  # def new
  #   @group = Group.new
  # end

  def events
     @group_events = current_organisation.events.all
  end

  def jobs
    @group_jobs = current_organisation.jobs.all
  end

  def skills
    @group_skills = current_organisation.users.all
  end

  def directory
    @group_directories = currrent_organisation.users.all
  end

  def invite
    redirect_to jobs_groups_url
  end

 def network
 end

  # def create
  #   @group = current_organisation.groups.build(group_params)
  #   if @group.save
  #     redirect_to  organisation_group_url(current_organisation.id,@group.id)
  #   else
  #     render 'new'
  #     end
  # end


   def show
     #@group = group.find(params[:id])
  end


private
  def group_params
    params.require(:group).permit(:group_name)
  end

end

app/views/groups/directory.html.erb
<div class="row wrapper border-bottom page-heading">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content text-center p-md">
                    <div class="row">
                        <div class="col-lg-3">
                        </div>
                         <%= form_tag(skillsearch_users_path, method: "get" )  %>
                        <div class="col-lg-5">
                            <div class="form-group">
                            <%= text_field_tag :search, nil, placeholder: "Search for a skill, profession, work experience or education eg. MEST", class: "form-control input-lg m-b" , required: true %>

                            </div>
                        </div>
                        <div class="col-lg-1">
                            <div class="form-group">
                                <%= submit_tag("Search", :class => "btn btn-primary" , :style => "margin-top: 0.4em;")    %>
                            </div>
                        </div>
                        <div class="col-lg-3">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-1">
        </div>
        <div class="col-lg-10">
            <div class="ibox-content border-bottom text-center p-md">
                <h4>Skills set list</h4>
            </div>
            <div class="ibox float-e-margins">
                <div class="ibox-content border-bottom text-center p-md">
                    <div class="row">
                    <%   for group_directory in   @group_directories do  %>
                        <div class="col-lg-3">
                            <div class="ibox float-e-margins">
                                <div class="ibox-content border-bottom text-center p-md" style="background-color: #1ab394; color: #ffffff; border: 1px solid #f1e4e4; box-shadow: #f4f4f4 0px 2px 2px 2px;">
                                    <br />
                                    <%= image_tag group_skill.user_pic.uthumb.url if group_skill.user_pic? %>
                                   <!-- <img src="http://res.cloudinary.com/necthub/image/upload/v1500854799/profile_hq1hjc.jpg" class="img-circle" style="border: 5px solid #ffffff" /> -->
                                    <br />
                                </div>
                                <div class="ibox-content border-bottom text-center p-md" style="border: 1px solid #f1e4e4;  box-shadow: #f4f4f4 0px 2px 2px 2px;">
                                    <%= group_directory.try(:first_name)%> <%= group_skill.try(:Last_name)%>

                                <hr />
                                     <%= group_directory.try(:phone_number) %>
                                <hr />
                                   <%= group_directory.try(:education) %>
                                </div>
                            </div>
                        </div>

                          <% end %>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-1">
        </div>
    </div>
</div>

app/views/groups/index.html.erb
<div class="row wrapper border-bottom page-heading">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content text-center p-md">
                    <div class="row">
                        <div class="col-lg-3">
                        </div>
                        <div class="col-lg-5">
                            <div class="form-group">
                                <input type="text" class="form-control input-lg m-b" placeholder="Search for person" />
                            </div>
                        </div>
                        <div class="col-lg-1">
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" style="margin-top: 0.4em;">Search</button>
                            </div>
                        </div>
                        <div class="col-lg-3">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-1 col-md-1">
        </div>
        <div class="col-lg-2 col-md-2">
            <div class="ibox float-e-margins">
                <div class="ibox-content border-bottom text-center p-md" style="background-color: #1ab394; color: #ffffff;">
                    <br />
                    <img src="http://res.cloudinary.com/necthub/image/upload/v1500854799/profile_hq1hjc.jpg" class="img-circle" style="border: 5px solid #ffffff" />
                    <br />
                </div>
                <div class="ibox-content border-bottom text-center p-md">
                    Chris Bimpong
                <hr />
                    Entrepreneur
                <hr />
                    MEST
                </div>
            </div>
        </div>
        <div class="col-lg-7 col-md-7">
                <% for group_announcement in @group_announcements do%>
                <div class="ibox-content border-bottom text-center p-md">
                    <div class="row">
                        <div class="col-lg-12" align="left">
                            <h3><%= group_announcement.try(:title)%></h3>
                            <hr />
                            <p>
                               <%= group_announcement.try(:description)%>
                            </p>
                            <hr />
                        </div>
                    </div>
                </div>
                <br />
                <%end%>
                <br />

            </div>

        </div>
        <div class="col-lg-2 col-md-1">
        </div>
    </div>
</div>

app/views/groups/network.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Network</h2>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content">

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="row">
                    <div class="col-lg-6" align="center">
                        <h2>Create Network</h2>
                    </div>
                    <div class="col-lg-6" align="center">
                        <%#<a href="" class="btn btn-primary">New Event</a>%>

                    </div>
                </div>

                </div>

            <div class="ibox-content text-center css-animation-box"><!-- Copy -->
                <br /><br />
                <h1 class="text-navy">Your Events</h1>
                <br /><br />



                <div class="row">


        <div class="col-lg-4">
            <div class="ibox" style="border: 1px solid #f1e4e4; padding: 0px;">
              <!--  <div class="ibox-title">
                     <h5></h5>
                 </div> -->
                <div class="ibox-content">
                    <div><!-- Image here    event_pic.nthumb.url if event.event_pic?  -->

                    </div>
                    <br />
                   <!-- <h4>Info</h4> -->
                    <p>

                    </p>
                    <br />

                </div>
            </div>
        </div>


    </div>

            </div>
            </div>
        </div>
    </div>

</div>

<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $('.summernote').summernote();

    var edit = function () {
        $('.click2edit').summernote({ focus: true });
    };

    $("#edit").click(function () {
        $('.click2edit').summernote({ focus: true });
    });

    $("#save").click(function () {
        var aHTML = $('.click2edit').code(); //save HTML If you need(aHTML: array).
        $('.click2edit').destroy();
    });

});

</script>

<% end %>